# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaHackaton', '0003_auto_20171125_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombreComercial',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ruc',
        ),
    ]
