# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaHackaton', '0004_auto_20171125_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombreComercial',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='ruc',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
