# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaHackaton', '0005_auto_20171125_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombreComercial',
            field=models.CharField(max_length=500, null='true'),
        ),
    ]
